DBPath: _testhoddb
Buildings:
    soda: testbuildings/berkeley.ttl
    test: testbuildings/example.ttl
BrickClassTTL: "testbuildings/Brick.ttl"
BrickFrameTTL: "testbuildings/BrickFrame.ttl"
ReloadBrick: false
DisableQueryCache: true
ShowNamespaces: false
ShowQueryPlan: false
ShowDependencyGraph: false
ShowQueryPlanLatencies: false
ShowOperationLatencies: false
ShowQueryLatencies: false
LogLevel: Critical
EnableBOSSWAVE: false
EnableHTTP: false
